#!/usr/bin/env bash
###############################################################################
# Dice roller for TTRPG
# Usage: dndd d4 1 2
# The arugment with the "d" is the die to roll, so d20 rolls a 20-sided die
# one time, 2d4 rolls a four-sided die two times and adds the results.
# If there is no number before the "d", the script assumes a die count of 1.
# Any numerical arugment that doesn't contain a "d" is added to the total.
# The order of arguments is irrelevant, so "dndd 1 2 4d5" rolls the same
# dice and add the same modifiers as "dndd 2 4d5 1"
###############################################################################

debug=true
modifier=0
numberofdice=1
dietype=6
unmoddedtotal=0
total=0

isanumber='^[0-9]+$'
hasad='d'
for arg in "$@"; do
  if [[ $arg =~ $isanumber ]]; then
    modifier=$((modifier+arg))
  elif [[ $arg =~ $hasad ]]; then
    # shellcheck  disable=SC2001
    dietype=$(echo "$arg" | sed -e 's/\([0-9]*\)d\([0-9][0-9]*\)/\2/')
    # shellcheck  disable=SC2001
    _numberofdice=$(echo "$arg" | sed -e 's/\([0-9]*\)d\([0-9][0-9]*\)/\1/')
  else
    echo "I do not know what to do with '$arg'" >&2
  fi
done

if [[ "$_numberofdice" =~ $isanumber ]]; then
  numberofdice=$_numberofdice
fi

$debug && echo "modifer=$modifier" >&2
$debug && echo "numberofdice=$numberofdice" >&2
$debug && echo "dietype=$dietype" >&2

rolls=0
while [[ $rolls -lt $numberofdice ]]; do
  letsroll=$(shuf -i 1-"${dietype}" -n 1)
  unmoddedtotal=$((unmoddedtotal+letsroll))  
  rolls=$((rolls+1))
done
total=$((unmoddedtotal+modifier))

$debug && echo "unmoddedtotal=$unmoddedtotal" >&2
$debug && echo "total=$total" >&2

echo $total
# End
